### ISSUE TITLE
On the triage screen, we no longer need to show separate options depending on whether they requested inspection

### ISSUE THREAD

**Issue by nonprofittechy** [LemmaLegalConsulting/docassemble-HousingCodeChecklist#408]
We used to show "enforce a inspection order" but we took that off as it's redundant with the sue your landlord option.

We should show just *one* list of options, regardless of inspection choice.

There is also some logic elsewhere in the interview that reflects this difference that we will be able to simplify now.

**Comment by miabonardi** [comment]
Working on this in [remove_separate_options_triage_from_old_enforce_order_option](https://github.com/LemmaLegalConsulting/docassemble-HousingCodeChecklist/tree/remove_separate_options_triage_from_old_enforce_order_option) branch. 

The contempt complaint is still relevant to the option "Tell my judge that the landlord is ignoring the judge's order" which should be selected when the user chooses "My landlord is ignoring a court order" but it is not. This is somewhat linked to #419.  

Instead, when "My landlord is ignoring a court order" is the only lawsuit selected, the normal "Ask a judge to order my landlord to fix a problem or sue my landlord for money" choice is pre-selected. 

I think the issue is in `set_document_choice_by_lawsuit_kind` but cannot find it

https://github.com/LemmaLegalConsulting/docassemble-HousingCodeChecklist/blob/44b2531af7d8e1dc28bf93cdf88c10732f3aa2b4/docassemble/HousingCodeChecklist/data/questions/housing_code_interview.yml#L1360-L1393
