### ISSUE TITLE
Investigate the start new form loop issue the audit found

### ISSUE THREAD

**Issue by KelizaMcGuire** [LemmaLegalConsulting/docassemble-HousingCodeChecklist#501]
<img width="1321" alt="Screenshot 2024-08-08 at 1 15 56 PM" src="https://github.com/user-attachments/assets/e15dbd8a-32d9-411f-9229-fde12c60fb61">

**Comment by KelizaMcGuire** [comment]
@nonprofittechy @ll-jgraszer This does seem to happen to me when I click start a new form. It opens a new tab that is the same screen, providing the option to start a new form again (or interviews in progress).

**Comment by nonprofittechy** [comment]
It turns out this was a misconfiguration on the Suffolk production server. I just fixed and tested. You might need to edit the url to add &reset=1 to re-load the configuration option. I don't think that will affect regular users--the old variables are just sticky for a few hours without that.

https://apps.suffolklitlab.org/interview?i=docassemble.AssemblyLine:data/questions/interview_list.yml&reset=1
